apiVersion: v1
kind: Service
metadata:
  name: service-ipcluster
  labels:
    app: service-ipcluster
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
