apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  labels:
    app: service-nodeport
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
      nodeport: 30080
